language: objective-c
osx_image: xcode8.2

before_install:
  - gem install cocoapods
  - gem install xcpretty --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild test -workspace Amble.xcworkspace -scheme Amble -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2' | xcpretty --color

notifications:
  email:
    on_success: never
    on_failure: always
