language: objective-c
osx_image: xcode8.2

before_install:
  - gem install cocoapods -v '1.2.0'

script:
  - xcodebuild -workspace amble-ios.xcworkspace -scheme amble-ios -sdk iphonesimulator

notifications:
  email:
    on_success: never
    on_failure: always
