language: objective-c
osx_image: xcode8.2

before_install:
  - gem install cocoapods -v '1.2.0'
  - gem install xcpretty
  - pod repo update

script:
  - xcodebuild test -workspace amble-ios.xcworkspace -scheme amble-ios -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.2' | xcpretty --color

notifications:
  email:
    on_success: never
    on_failure: always
